version: '3.8'

services:
  nginx-server:
    image: nginx
    volumes:
      - './dist/:/usr/share/nginx/html/'
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './secret/:/etc/nginx/'
    ports: 
      - 80:80/tcp
      - 443:443/tcp
